#!/usr/bin/env bash

if [[ -z "${DEVELOPER_DIR:-}" && -d "/Applications/Xcode.app/Contents/Developer" ]]; then
  export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
fi

LOCALAGENT_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCALAGENT_ROOT="$(cd "$LOCALAGENT_SCRIPT_DIR/../.." && pwd)"
LOCALAGENT_NATIVE_ROOT="$LOCALAGENT_ROOT/ThirdParty/OpenMinisNative"
LOCALAGENT_NATIVE_LOCK="$LOCALAGENT_NATIVE_ROOT/native-sources.lock"
platform="${LOCALAGENT_NATIVE_PLATFORM:-${PLATFORM_NAME:-${SDK_NAME:-iphoneos}}}"

case "$platform" in
  iphoneos*)
    LOCALAGENT_NATIVE_PLATFORM=iphoneos
    LOCALAGENT_NATIVE_MIN_VERSION_FLAG="-miphoneos-version-min=17.0"
    LOCALAGENT_NATIVE_SUPPORTED_PLATFORM=iPhoneOS
    ;;
  iphonesimulator*)
    LOCALAGENT_NATIVE_PLATFORM=iphonesimulator
    LOCALAGENT_NATIVE_MIN_VERSION_FLAG="-mios-simulator-version-min=17.0"
    LOCALAGENT_NATIVE_SUPPORTED_PLATFORM=iPhoneSimulator
    ;;
  *)
    echo "native.unsupported_platform: $platform" >&2
    return 2
    ;;
esac

LOCALAGENT_NATIVE_BUILD_ROOT="$LOCALAGENT_NATIVE_ROOT/.build/work/$LOCALAGENT_NATIVE_PLATFORM"
LOCALAGENT_NATIVE_ARTIFACT_ROOT="$LOCALAGENT_NATIVE_ROOT/.build/$LOCALAGENT_NATIVE_PLATFORM"
LOCALAGENT_NATIVE_DOWNLOAD_ROOT="$LOCALAGENT_NATIVE_ROOT/.build/downloads"
LOCALAGENT_NATIVE_SOURCE_ROOT="$LOCALAGENT_NATIVE_ROOT/.build/sources"
LOCALAGENT_NATIVE_RESOURCE_ROOT="$LOCALAGENT_NATIVE_ROOT/.build/resources"

export LOCALAGENT_ROOT
export LOCALAGENT_NATIVE_ROOT
export LOCALAGENT_NATIVE_LOCK
export LOCALAGENT_NATIVE_PLATFORM
export LOCALAGENT_NATIVE_MIN_VERSION_FLAG
export LOCALAGENT_NATIVE_SUPPORTED_PLATFORM
export LOCALAGENT_NATIVE_BUILD_ROOT
export LOCALAGENT_NATIVE_ARTIFACT_ROOT
export LOCALAGENT_NATIVE_DOWNLOAD_ROOT
export LOCALAGENT_NATIVE_SOURCE_ROOT
export LOCALAGENT_NATIVE_RESOURCE_ROOT

# Compatibility aliases keep the copied build logic small while all public
# inputs and outputs use the LocalAgent naming and directory contract.
export OPENMINIS_PLATFORM="$LOCALAGENT_NATIVE_PLATFORM"
export OPENMINIS_MIN_VERSION_FLAG="$LOCALAGENT_NATIVE_MIN_VERSION_FLAG"
export OPENMINIS_SUPPORTED_PLATFORM="$LOCALAGENT_NATIVE_SUPPORTED_PLATFORM"
export OPENMINIS_NATIVE_BUILD_ROOT="$LOCALAGENT_NATIVE_BUILD_ROOT"
export OPENMINIS_NATIVE_ARTIFACT_ROOT="$LOCALAGENT_NATIVE_ARTIFACT_ROOT"
